name: 🙇 Feature Request
description: Suggest new functionality, new content or balancing changes
title: "[Feature]: "
labels: [suggestion]
assignees:
  - Ejektaflex
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: what-want
    attributes:
      label: Feature Description
      description: "What you want added to Bountiful (A clear and concise description of what you want to have added/improved):"
      placeholder: Tell us what you'd like!
    validations:
      required: true
  - type: textarea
    id: better
    attributes:
      label: Feature Benefits
      description: Tell us how this would make Bountiful better
    validations:
      required: true
